### ISSUE TITLE
Can not search in Django Admin List 

### ISSUE THREAD

**Issue by Star-fly-Cheng** [luojilab/django-mirage-field#11]
```
id          |           phone
---------------------+--------------------------
 123 | -bYijegsEDrmS1s7ilnspA==

```
```
obj = TestModel.objects.get(phone=18866677777)
obj.id          # 123
obj.phone       # 18866677777
type(obj.phone) # int
```

```
#admin.py
search_fields = ['phone']
```

In Django Admin, I can search by '-bYijegsEDrmS1s7ilnspA==', but I cannot search by '18866677777'.

**Comment by tcitry** [comment]
@Star-fly-Cheng 
Yes... See the source code below. Django didn't use ORM search method in Admin list, I suggest you rewrite this function `get_search_results`, like:

```Python
@admin.register(TestModel)
class TestAdmin(admin.ModelAdmin):
    search_fields = ['phone']

    def get_search_results(self, request, queryset, search_term):
        # write your code here
        return queryset, use_distinct
```

xxx/venv/lib/python3.6/site-packages/django/contrib/admin/options.py

![image](https://user-images.githubusercontent.com/5220740/95981535-6126ba80-0e51-11eb-847d-1b6a46d13bff.png)

**Comment by r1bnc** [comment]
I have the same issue but with Django Q() `from django.db.models import Q` objects filter. Q object filter() returns encrypted data instead of decrypted.

**Comment by tcitry** [comment]
@r1bnc yes, `mirage` also not support Q query yet, you can manual use `decrypt` method by import `Crypto`

``` python
from mirage.crypto import Crypto
c = Crypto(key="")                      # key is optional, default will use settings.SECRET_KEY
text = c.decrypt('-bYijegsEDrmS1s7ilnspA==')
```

**Comment by r1bnc** [comment]
Yeah but I don't know how to integrate that to Q query at this moment.
