### ISSUE TITLE
ECB mode not recommended

### ISSUE THREAD

**Issue by severindellsperger** [luojilab/django-mirage-field#15]
Hi,

Thanks for the helpful implementation.
Is it possible to change ECB mode with CBC mode?
ECB mode is definitely not recommended because it's weak.

Best,
Severin

**Comment by tcitry** [comment]
@severindellsperger Hi. thanks or your issue.

Yes, ECB mode is weak than CBC, but recently I'm very busy, I can't promise when release CBC.

But PR is always welcome, you can switch to a 2.0 branch to build this good idea.

**Comment by Brawn1** [comment]
Hy,

what is the recommend way, to switch from ECB to CBC?
I think, we integrate a tool in management, and add a settings to change self from ECB to CBC.
So when the mode is changed, and no migration or tool is running before, all encrypted fields can't decrypt any more.

**Comment by tcitry** [comment]
@Brawn1 Hey

Yes...ECB is a problem now...

I'll try a way that can easy expand encrypt/decrypt method to support other like CBC, please wait some days...

**Comment by tcitry** [comment]
@severindellsperger @Brawn1 

Good news!

I have suppor CBC with version `2.0.0b1`, please have a try, if no bugs I'll release ASAP.

https://pypi.org/manage/project/django-mirage-field/release/2.0.0b1/

**Comment by severindellsperger** [comment]
Hi @tcitry 

Sounds awesome. I'm currently on vacation and have no time to test it. @Brawn1 can you verify it?

Thanks,
severindellsperger

**Comment by tcitry** [comment]
Published with `1.2.0` ！
