### ISSUE TITLE
Strange issue with Python 3.7 and 3.8

### ISSUE THREAD

**Issue by ZviBaratz** [luojilab/django-mirage-field#20]
Hi,

I'm developing a Django application, and even though everything works fine in my local dev environment (Python 3.9), my CI build for Python 3.7 and 3.8 is failing (surprisingly, Python 3.6 is passing, and so is 3.9).
The exception I'm getting looks like this:
```bash
  File "/root/pylabber/accounts/models/__init__.py", line 9, in <module>
    from accounts.models.export_destination import ExportDestination
  File "/root/pylabber/accounts/models/export_destination.py", line 15, in <module>
    class ExportDestination(TitleDescriptionModel):
  File "/root/pylabber/accounts/models/export_destination.py", line 29, in ExportDestination
    password = fields.EncryptedCharField(
  File "/root/pylabber/.tox/py38-django3/lib/python3.8/site-packages/mirage/fields.py", line 13, in __init__
    self.crypto = Crypto(key)
  File "/root/pylabber/.tox/py38-django3/lib/python3.8/site-packages/mirage/crypto.py", line 60, in __init__
    assert len(key) >= 32, "mirage key length must more than 32!"
AssertionError: mirage key length must more than 32!

```
The relevant field definition looks like:
```python
class ExportDestination(TitleDescriptionModel):
    ...
    password = fields.EncryptedCharField(
        max_length=128, blank=False, null=False
    )
```
Any help figuring out the cause for this would be greatly appreciated. 
Thanks for all your great work,
Zvi

**Comment by tcitry** [comment]
Hi @ZviBaratz 

Are you make sure your `MIRAGE_SECRET_KEY` or `SECRET_KEY` in settings.py that length is >= 32?

or maybe something wrong in your CI environment variable, did you set it in CI ?

**Comment by ZviBaratz** [comment]
Well, that's embarrassing. I forgot about the default SECRET_KEY setting used in the CI environment. 
I made a tiny PR with a more verbose message for that exception, hope you agree it's a little clearer (there is also a small typo in the current one).
Thank you very much for your support!

**Comment by tcitry** [comment]
That's great! Thanks for your PR.
