### ISSUE TITLE
Is it possible to add encrypted JSON fields?

### ISSUE THREAD

**Issue by riquedev** [luojilab/django-mirage-field#24]
Hello, it's me again!!
Congratulations for the great work with this repository, it has become essential in several projects of my team.
Currently we are using the JSONField (models.JSONField), as it was done in the URLField is it possible to do the same with the JSON?
The reason is that in some external API returns there are data that I would like to have encrypted inside the database and with mirage it would be a more ideal way since that is what I have used in absolutely all cases.

**Comment by tcitry** [comment]
Thanks for report, I'll think about it in recent days.

**Comment by tcitry** [comment]
@riquedev Hi, I have add `EncryptedJSONField` to support JSONField with version `1.4.0`, I wrote a simple testcase but I didn't use it in my production environment to have to complete test, if there has bugs please contact me again.
