### ISSUE TITLE
Is this repository still maintained?

### ISSUE THREAD

**Issue by hr23232323** [luojilab/django-mirage-field#25]
Hello, 

The original maintainer @tcitry mentioned in this [commit](https://github.com/luojilab/django-mirage-field/commit/612f8f5008a0fb4ca139d5638810f136ed3d7e58) that he'll no longer be maintaining django-mirage-field. Could you clarify if this repository is still being maintained or not?

Thanks!

**Comment by tcitry** [comment]
I'm not sure the administer whether or not kick me out of the org in the future, for this reason, I'd rather maintain this project by the [fork](https://github.com/tcitry/django-mirage-field) version.

**Comment by hr23232323** [comment]
That makes sense. My concern is that if we use `pip install django-mirage-field` to install the package and you make changes to the [fork](https://github.com/tcitry/django-mirage-field) version, then how do we get those updates?

**Comment by tcitry** [comment]
Yes, you can still use `pip` to install the fork project, I own the PYPI account.

**Comment by hr23232323** [comment]
Great, thanks for confirming!
