### ISSUE TITLE
Can't read SECRET_KEY setted with django-configurations

### ISSUE THREAD

**Issue by trottomv** [luojilab/django-mirage-field#7]
Hi, I've tried tu use django-mirage-fields and i use django-configurations for vars settings,
mirage can't read SECRET_KEY.

**settings.py**
```
from configurations import Configuration, values

class MyProject(Configuration):
    SECRET_KEY = values.SecretValue()
```

**.env**
```
DJANGO_SECRET_KEY=SecretSecretSecretSecretSecretSecret
```

values of SECRET_KEY returned by mirage is `None`

Is there a way to set another default KEY for mirage?

**Comment by tcitry** [comment]
@trottomv Hi, thanks for the issue.

I just took a look at django-configurations and test in my local, and are you sure your app has readed the `.env`? Or, have you `export DJANGO_SECRET_KEY='SecretSecretSecretSecretSecretSecret` to your local environment variable?

**Comment by tcitry** [comment]
@trottomv Maybe next version, I'll add a `MIRAGE_SECRET_KEY` in settings.py, it will get first, if not set, mirage will use SECRET_KEY

**Comment by trottomv** [comment]
@tcitry MIRAGE_SECRET_KEY option could be very helpful,
I've finally succesfully configured mirage with django-configurations, I had probably set some variables wrong in the .env
thanks very much.

**Comment by tcitry** [comment]
@trottomv I have Added `MIRAGE_SECRET_KEY`, see [1.1.0](https://github.com/luojilab/django-mirage-field/releases/tag/1.1.0)
